---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by justi.
--- DateTime: 2024/7/11 11:52
---

function love.load()
    print("love load");
end



function love.update(dt)
    print(dt);
end