---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by justi.
--- DateTime: 2024/7/11 11:52
---



function love.load()
    img =love.graphics.newImage("someArts/red.png");
end

function love.draw()
    love.graphics.draw(img,0,0);
end


function love.update(dt)
   -- print(dt);
end