---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by justi.
--- DateTime: 2024/7/11 12:03
---
Node =Object:extend()

function Node:init(args)
    args=args or {}
    args.T =args.T or {}
    self.ARGS=self.ARGS or {}
    self.RETS={}

    self.config =self.config or {}

    self.T ={
        x =args.T.x or args.T[1] or 0,
        y=args.T.y or args.T[2] or 0,
        w =args.T.w or args.T[3] or 1,
        h =args.T.h or args.T[4] or 1,
        r =args.T.r or args.T[5] or 0,
        scale =args.T.scale or args.T[6] or 1;
    }

    self.CT=self.T;
    self.click_offset ={x=0,y=0}
    self.hover_offset={x=0,y=0}
    self.created_on_pause=G.SETTINGS.paused;
    G.ID =G.ID or 1;
    self.ID =G.ID;
    G.ID =G.ID+1;
    self.FRAME={
        DRAW=-1,
        MOVE=-1
    }

    self.states ={
        visible =true,
        collide ={can=false,is=false},
        focus ={can=false,is=false},
        hover ={can=true,is=false};
        click={can=true,is=false};
        drag={can=true,is=false};
        release_on={can=true,is=false};
    }

    self.container =args.container or G.ROOM

    if not self.children then
        self.children={}
    end

    if getmetatable(self)==Node then
        table.insert(G.I.NODE,self);
    end

    if not G.STAGE_OBJECT_INTERRUPT then

        table.insert(G.STAGE_OBJECTS[G.STAGE],self);
    end
end

function Node:draw_boundingrect()
    self.under_overlay=G.under_overlay;
    if G.DEBUG then
        local transform =self.VT or self.T;
        love.graphics.push()
        love.graphics.scale(G.TILESCALE,G.TILESCALE);
        love.graphics.translate(transform.x*G.TILESIZE+transform.w*G.TILESIZE*0.5,
                                transform.y*G.TILESIZE+transform.h*G.TILESIZE*.5);
        love.graphics.rotate(transform.r);
        love.graphics.translate(-transform.w*G,TILESIZE*0.5,-transform.h*G.TILESIZE*0.5);

        if self.DEBUG_VALUE then
            love.graphics.setColor(1,1,0,1);
            love.graphics.print((self.DEBUG_VALUE or ''),transform.w*G.TILESIZE,transform.h*G.TILESIZE,nil,1/G.TILESCALE)
        end
    end
end